sudo: required
services:
  - docker

before_install:
  - docker build -t pauloalexandre3d/frontendasdevops -f Dockerfile.dev .

script:
  - docker run pauloalexandre3d/frontendasdevops npm run test -- --coverage