sudo: required
services:
  - docker

before_install:
  - docker build -t pauloalexandre/frontendAsDevops -f Dockerfile.dev .

script:
  - docker run pauloalexandre/frontendAsDevops npm run test -- --coverage