sudo: required
services:
  - docker

before_install:
  - docker build -t pauloalexandre3d/frontendasdevops -f Dockerfile.dev .

script:
  - docker run -e CI=true pauloalexandre3d/frontendasdevops npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east"
  app: "frontendasdevops"
  env: "Frontendasdevops-env"
  bucket_name: "elasticbeanstalk-us-east-2-309026106143"
  bucket_path: "frontendasdevops"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"