sudo: required
services:
  - docker

before_install:
  - docker build -t pauloalexandre3d/frontendasdevops -f Dockerfile.dev .

script:
  - docker run -e CI=true pauloalexandre3d/frontendasdevops npm run test